/**
 * Pine Script v5 generation.
 *
 * Kronos validates a strategy; TradingView is where you actually watch it and
 * where alerts fire from. This module renders a Kronos strategy as a Pine
 * `strategy()` script whose entries carry an `alert_message` containing the JSON
 * payload the Kronos webhook expects — so one "Any alert() function call" alert
 * on TradingView drives paper fills here.
 *
 * The generated script mirrors the same parameters the backtester used, but
 * understand what that does and does not buy you: TradingView's engine is not
 * this one. Bar timing, fill assumptions and data source all differ, so treat
 * the Pine version as the alerting front-end for a strategy Kronos already
 * validated — not as an independent confirmation of it.
 *
 * Pure string generation, no I/O, so it unit-tests directly.
 */

export type PineOptions = {
  strategyName: string;
  kind: string;
  params: Record<string, unknown>;
  /** Absolute URL of the Kronos webhook endpoint. */
  webhookUrl: string;
  /** Shared secret; embedded in the alert payload since TradingView cannot send headers. */
  secret: string;
  commissionBps?: number;
  slippageBps?: number;
};

function num(params: Record<string, unknown>, key: string, fallback: number): number {
  const v = params[key];
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}

function bool(params: Record<string, unknown>, key: string, fallback = false): boolean {
  const v = params[key];
  return typeof v === "boolean" ? v : fallback;
}

/**
 * Pine string literals are single-quoted here, so any single quote or backslash
 * in user-supplied text would break the script. Strip rather than escape:
 * a mangled strategy name is a cosmetic problem, a broken script is not.
 */
function pineSafe(s: string): string {
  return s.replace(/[\\'"\n\r]/g, " ").trim();
}

function header(o: PineOptions): string {
  const commissionPct = (o.commissionBps ?? 5) / 100;
  const slippageBps = Math.max(0, o.slippageBps ?? 2);
  return `//@version=5
// Generated by Kronos. Strategy: ${pineSafe(o.strategyName)}
//
// Setup:
//   1. Paste into TradingView → Pine Editor → Add to chart.
//   2. Create an alert on THIS script.
//   3. Condition: "${pineSafe(o.strategyName)}", trigger "alert() function calls only".
//   4. Notifications → Webhook URL:
//        ${o.webhookUrl}
//   5. Leave the alert message box EMPTY — the script supplies the JSON itself.
//
// The webhook fills a paper order in Kronos. It never touches real money.
// Costs. Commission converts exactly — Kronos charges ${o.commissionBps ?? 5} bps of notional
// and Pine's percent model is the same quantity scaled. Slippage does not:
// Pine counts it in *ticks*, which are absolute, while Kronos models it in basis
// points, which are relative, so the conversion depends on the symbol's mintick
// and its price and cannot be baked in here. It is left at 0, which means
// TradingView's own Strategy Tester will read slightly better than reality.
// Kronos validated this strategy with ${slippageBps} bps of slippage included; at price P
// that is about P * ${slippageBps} / 10000 / syminfo.mintick ticks if you want to set it
// by hand. Either way, trust the Kronos verdict over the Pine one.
strategy("Kronos · ${pineSafe(o.strategyName)}", overlay=true,
     default_qty_type=strategy.percent_of_equity, default_qty_value=100,
     commission_type=strategy.commission.percent, commission_value=${commissionPct},
     slippage=0,
     initial_capital=10000)

// --- Kronos webhook payload -------------------------------------------------
// TradingView cannot send custom headers, so the shared secret travels in the
// body. Treat this script as a credential: anyone holding it can post signals
// into your Kronos instance.
kronosPayload(action) =>
    '{"secret":"${pineSafe(o.secret)}"' +
      ',"symbol":"' + syminfo.ticker + '"' +
      ',"action":"' + action + '"' +
      ',"price":"' + str.tostring(close) + '"' +
      ',"strategy":"${pineSafe(o.strategyName)}"' +
      ',"time":"' + str.tostring(time) + '"}'
`;
}

const FOOTER = `
// --- Execution --------------------------------------------------------------
if goLong and strategy.position_size <= 0
    strategy.entry("Long", strategy.long, alert_message=kronosPayload("buy"))

if goShort and allowShort and strategy.position_size >= 0
    strategy.entry("Short", strategy.short, alert_message=kronosPayload("sell"))

if goFlat and strategy.position_size != 0 and not allowShort
    strategy.close_all(alert_message=kronosPayload("flat"))
`;

/** Render a Kronos strategy as a Pine v5 script. */
export function toPineScript(o: PineOptions): string {
  switch (o.kind) {
    case "SMA_CROSSOVER": {
      const fast = num(o.params, "fast", 20);
      const slow = num(o.params, "slow", 50);
      return `${header(o)}
// --- Signal: SMA crossover --------------------------------------------------
fastLen = input.int(${fast}, "Fast length", minval=2)
slowLen = input.int(${slow}, "Slow length", minval=3)
allowShort = input.bool(${bool(o.params, "allowShort")}, "Allow shorts")

fast = ta.sma(close, fastLen)
slow = ta.sma(close, slowLen)
plot(fast, "Fast SMA", color=color.new(color.teal, 0))
plot(slow, "Slow SMA", color=color.new(color.orange, 0))

goLong = ta.crossover(fast, slow)
goShort = ta.crossunder(fast, slow)
goFlat = goShort
${FOOTER}`;
    }

    case "RSI_REVERSION": {
      const period = num(o.params, "period", 14);
      const oversold = num(o.params, "oversold", 30);
      const overbought = num(o.params, "overbought", 70);
      return `${header(o)}
// --- Signal: RSI mean reversion ---------------------------------------------
rsiLen = input.int(${period}, "RSI length", minval=2)
osLevel = input.float(${oversold}, "Oversold")
obLevel = input.float(${overbought}, "Overbought")
allowShort = input.bool(${bool(o.params, "allowShort")}, "Allow shorts")

r = ta.rsi(close, rsiLen)
mid = (osLevel + obLevel) / 2
plot(r, "RSI", color=color.new(color.purple, 0))
hline(osLevel, "Oversold")
hline(obLevel, "Overbought")

// Enter on the extreme, leave when RSI recovers through the midline — the same
// stateful behaviour the Kronos implementation uses.
goLong = ta.crossunder(r, osLevel)
goShort = ta.crossover(r, obLevel)
goFlat = ta.crossover(r, mid)
${FOOTER}`;
    }

    case "DONCHIAN_BREAKOUT": {
      const entryPeriod = num(o.params, "entryPeriod", 20);
      const exitPeriod = num(o.params, "exitPeriod", 10);
      return `${header(o)}
// --- Signal: Donchian breakout ----------------------------------------------
entryLen = input.int(${entryPeriod}, "Entry channel", minval=2)
exitLen = input.int(${exitPeriod}, "Exit channel", minval=2)
allowShort = input.bool(${bool(o.params, "allowShort")}, "Allow shorts")

// [1] excludes the current bar, matching Kronos. Including it would make a
// breakout trivially true on the bar that sets the high.
entryHigh = ta.highest(high, entryLen)[1]
entryLow = ta.lowest(low, entryLen)[1]
exitHigh = ta.highest(high, exitLen)[1]
exitLow = ta.lowest(low, exitLen)[1]
plot(entryHigh, "Entry high", color=color.new(color.green, 40))
plot(entryLow, "Entry low", color=color.new(color.red, 40))

goLong = close > entryHigh
goShort = close < entryLow
goFlat = close < exitLow
${FOOTER}`;
    }

    case "MACD_TREND": {
      const fast = num(o.params, "fast", 12);
      const slow = num(o.params, "slow", 26);
      const signal = num(o.params, "signal", 9);
      return `${header(o)}
// --- Signal: MACD trend -----------------------------------------------------
fastLen = input.int(${fast}, "Fast", minval=2)
slowLen = input.int(${slow}, "Slow", minval=3)
sigLen = input.int(${signal}, "Signal", minval=2)
allowShort = input.bool(${bool(o.params, "allowShort")}, "Allow shorts")

[macdLine, signalLine, hist] = ta.macd(close, fastLen, slowLen, sigLen)
plot(macdLine, "MACD", color=color.new(color.blue, 0))
plot(signalLine, "Signal", color=color.new(color.orange, 0))

goLong = ta.crossover(macdLine, signalLine)
goShort = ta.crossunder(macdLine, signalLine)
goFlat = goShort
${FOOTER}`;
    }

    default:
      throw new Error(`No Pine template for strategy kind: ${o.kind}`);
  }
}

/** Kinds that can currently be exported. */
export const PINE_SUPPORTED = [
  "SMA_CROSSOVER",
  "RSI_REVERSION",
  "DONCHIAN_BREAKOUT",
  "MACD_TREND",
] as const;

export function canExportPine(kind: string): boolean {
  return (PINE_SUPPORTED as readonly string[]).includes(kind);
}
